#!/bin/bash
rrdtool create /home/MMB/BMP280.rrd --step 5 \
DS:Temperatur:GAUGE:600:-30:100 \
DS:Pressur:GAUGE:600:900:1100 \
RRA:AVERAGE:0.5:5s:1d \
RRA:AVERAGE:0.5:1m:30d \
RRA:AVERAGE:0.5:10m:1y \
RRA:AVERAGE:0.5:1d:10y \
RRA:MIN:0.5:1d:20y \
RRA:MAX:0.5:1d:20y
